package com.finalis.mobile.core.model

enum class BroadcastErrorCode {
    BAD_TX_HEX,
    TX_PARSE_FAILED,
    VALIDATION_FAILED,
    TX_DUPLICATE,
    TX_MISSING_OR_UNCONFIRMED_INPUT,
    TX_FEE_BELOW_MIN_RELAY,
    MEMPOOL_FULL_NOT_GOOD_ENOUGH,
    RELAY_UNAVAILABLE,
    UNKNOWN_REJECTION,
    UPSTREAM_UNAVAILABLE,
    UPSTREAM_MALFORMED,
    INTERNAL_ERROR,
}
