package com.finalis.mobile.core.model

data class NetworkIdentity(
    val name: String,
    val tipHeight: Long,
    val tipHash: String,
    val serverTruth: String,
    val proofsTipOnly: Boolean,
    val networkId: String? = null,
    val protocolVersion: Int = 0,
    val featureFlags: Long = 0L,
    val genesisHash: String? = null,
    val finalizedHeight: Long? = null,
    val finalizedHash: String? = null,
    val healthyPeerCount: Int? = null,
    val establishedPeerCount: Int? = null,
    val version: String? = null,
    val binary: String? = null,
    val binaryVersion: String? = null,
    val walletApiVersion: String? = null,
    val syncMode: String? = null,
    val syncSnapshotPresent: Boolean? = null,
    val localFinalizedHeight: Long? = null,
    val observedNetworkHeightKnown: Boolean? = null,
    val observedNetworkFinalizedHeight: Long? = null,
    val finalizedLag: Long? = null,
    val bootstrapSyncIncomplete: Boolean? = null,
    val peerHeightDisagreement: Boolean? = null,
    val nextHeightCommitteeAvailable: Boolean? = null,
    val nextHeightProposerAvailable: Boolean? = null,
    val checkpointDerivationMode: String? = null,
    val checkpointFallbackReason: String? = null,
    val fallbackSticky: Boolean? = null,
    val qualifiedDepth: Long? = null,
    val adaptiveTargetCommitteeSize: Long? = null,
    val adaptiveMinEligible: Long? = null,
    val adaptiveMinBond: Long? = null,
    val adaptiveSlack: Long? = null,
    val targetExpandStreak: Long? = null,
    val targetContractStreak: Long? = null,
    val adaptiveFallbackRateBps: Long? = null,
    val adaptiveStickyFallbackRateBps: Long? = null,
    val adaptiveFallbackWindowEpochs: Long? = null,
    val adaptiveNearThresholdOperation: Boolean? = null,
    val adaptiveProlongedExpandBuildup: Boolean? = null,
    val adaptiveProlongedContractBuildup: Boolean? = null,
    val adaptiveRepeatedStickyFallback: Boolean? = null,
    val adaptiveDepthCollapseAfterBondIncrease: Boolean? = null,
    val adaptiveTelemetryWindowEpochs: Long? = null,
    val adaptiveTelemetrySampleCount: Long? = null,
    val adaptiveTelemetryFallbackEpochs: Long? = null,
    val adaptiveTelemetryStickyFallbackEpochs: Long? = null,
)
